

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


# numpy my submission

In [21]:
#insert titel image
#from  IPython.display import Image
#from IPython.core.display import HTML 
#x = Image("https://www.freecodecamp.org/news/content/images/size/w2000/2020/07/numpy.png")

HTTPError: HTTP Error 403: Forbidden

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [6]:
a = np.zeros(10)
a[4]=5
print(a)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [10]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [32]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

a = [1,2,0,0,4,0]

In [36]:
#These the indices in list a which are not of value 0
np.nonzero(a)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [38]:
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [42]:
rdm_array_3x3 = np.random.random((3,3,3))
print(rdm_array_3x3)

[[[0.6601585  0.04880311 0.97796652]
  [0.13604897 0.6538631  0.30242104]
  [0.46220408 0.93292837 0.08777029]]

 [[0.13327901 0.19811316 0.87223747]
  [0.01811168 0.77821316 0.55126856]
  [0.5094073  0.45497273 0.69508561]]

 [[0.22252481 0.37553347 0.25408442]
  [0.01319662 0.46958962 0.01113771]
  [0.54179505 0.13317714 0.41122523]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [43]:
rdm_array_10x10     = np.random.random((10,10))
min_rdm_array_10x10 = np.min(rdm_array_10x10)
max_rdm_array_10x10 = np.max(rdm_array_10x10)

print(min_rdm_array_10x10)
print(max_rdm_array_10x10)


0.011585799740944536
0.9872045233676536


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [71]:
rdm_vector_size_30 = np.random.random(30)
print(rdm_vector_size_30)

[0.55519827 0.590015   0.78954783 0.4966741  0.88823368 0.91411866
 0.99967618 0.79586415 0.93525678 0.83930428 0.41095198 0.00646148
 0.12546528 0.95928202 0.56845162 0.82688835 0.97182671 0.545065
 0.81619538 0.85483115 0.23979142 0.07760346 0.63563491 0.14318751
 0.17203388 0.67275665 0.6855356  0.78454731 0.91760979 0.73651397]


In [68]:
rdm_vector_size_30 = np.random.shuffle(rdm_vector_size_30)
print(vector_size_30)

TypeError: object of type 'NoneType' has no len()

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [185]:
print(np.diag([1,2,3,4], k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [91]:
#transposed the array with np.rot90 and than flipped from right to left with fliplr)
lst_lst.T == np.rot90(np.fliplr(lst_lst))
print(lst_lst.T)

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`


In [97]:
#Creating a random 5x5 array
a            = np.random.random((5,5))
print(a)

[[0.6450848  0.59543538 0.75951743 0.69301582 0.23447584]
 [0.47133749 0.19870452 0.04060604 0.05434304 0.46845328]
 [0.27647368 0.66251715 0.91808716 0.91245418 0.54641861]
 [0.27323062 0.64945934 0.05423301 0.0063324  0.25220276]
 [0.21673764 0.24381633 0.78724871 0.84290245 0.65643445]]


In [96]:
#Using np.linalg.norm function to normalize 5x5 array with gaussian distribution
Normalized_a = a / np.linalg.norm(a)
print(Normalized_a)

[[0.12837985 0.14762567 0.09032371 0.07178388 0.18863884]
 [0.27375527 0.13308319 0.01385233 0.21446314 0.07504518]
 [0.13403653 0.29681436 0.1595645  0.27561379 0.27756942]
 [0.03849231 0.10006301 0.30363448 0.0771259  0.20627652]
 [0.2741443  0.30233297 0.3155439  0.12260004 0.2246763 ]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [108]:
#4x4 array a
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#4x4 array b; both have intentional overlap
b= np.arange(12,28).reshape((4,4))
print(b)

In [110]:
#Using intersect1d (the vector of 2d spanning plane) 
a_b_intersect = np.intersect1d(a,b)
print(a_b_intersect)

[12 13 14 15]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [113]:
#Creating rnd vector size 10 and showcase size is 10
a = np.random.random(10)
print(a)
np.size(a)

10

In [114]:
#sorting the random vector a with sort function
np.sort(a)
print(a)

[0.4301376  0.74164713 0.97233594 0.78986706 0.69697613 0.24549067
 0.7357147  0.44046383 0.22755548 0.34855052]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [115]:
#Creating rnd vector size 10 and showcase size is 10
a = np.random.random(10)
print(a)
np.size(a)

[0.71408382 0.03251791 0.13240782 0.43058727 0.00678554 0.40873004
 0.69631004 0.40791367 0.67355353 0.21079376]


10

In [140]:
#Search index of max value of axis (in this case just one axis, )
a_i_max = np.argmax(a)
print(a_i_max)

0


In [142]:
#repalces the a[a_i_max] with 0
g = np.where(a==a[a_i_max], 0, a) 

[0.         0.03251791 0.13240782 0.43058727 0.00678554 0.40873004
 0.69631004 0.40791367 0.67355353 0.21079376]


array([0.29995996])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [160]:
#create random array 5x5
m = np.arange(25).reshape((5,5))
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [189]:
#mean of m in axis=0 (columns)
mean_rows = np.mean(m, axis=1, keepdims=True)
print(mean_rows)

[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]


In [190]:
#Subtract the mean of each row of a matrix
m_sub = m-mean_rows
print(m_sub)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


In [138]:
#Z is BIG array - how to get n highest numbers
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)

[3756 4108  885 ... 6354 7084 2401]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

## What is NP Argsort?
argsort() function is used to perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as arr that would sort the array.

## What does NP Argpartition do?
argpartition() function is used to create a indirect partitioned copy of input array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array.

In [221]:
Y= np.argsort(np.argpartition(Z,n))
print(Y)

[3325 4999 9999 ... 9997 9998    0]


In [196]:
Y= np.argsort(Z)
print(Y)

[3325 9753 4134 ... 9217  978 8359]


In [209]:
Z= np.argsort(Z)
print(Z)

values_n_degree=Z[(10000-n):10000]

[3325 4999 9999 ... 9997 9998    0]


In [210]:
np.argpartition(Z,n)

array([9999, 4999, 1442, ..., 9997, 9998,    2])

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [220]:
o = np.random.random((5,3))
for i in o:
    o = np.where(o > 4, i**i, o)
print(o)

[[0.9976507  0.14644817 0.52652113]
 [0.53525864 0.06332204 0.28563706]
 [0.96385137 0.92402922 0.07464264]
 [0.26820535 0.31880498 0.79767271]
 [0.34578626 0.50925609 0.35618563]]


In [213]:
#EXAMPLE FROM THE WEB
print(an_array)
OUTPUT
[ 3 23 5 67 12 15 89]

an_array = np.where(an_array > 20, 0, an_array)

print(an_array)
OUTPUT
[ 3  0  5  0 12 15  0]


SyntaxError: invalid syntax (154722379.py, line 4)